name: mobile_holo

description: "a open source project for mobile holo"

publish_to: "none"

version: 1.0.3+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  html: ^0.15.6
  pointycastle: ^3.7.3
  encrypt: ^5.0.3
  video_player: ^2.10.1
  shared_preferences: ^2.5.4
  canvas_danmaku: ^0.3.1
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  screen_brightness: ^2.1.7
  simple_gesture_detector: ^0.2.1
  volume_controller: ^3.4.1
  cached_network_image: ^3.4.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.7 #flutter pub run build_runner build
  package_rename: ^1.10.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/launcher.png

package_rename_config:
  android:
    app_name: "Holo"
    bundle_name: "Holo"
    package_name: "com.github.qiqd.holo"

  ios:
    app_name: "Holo"
    bundle_name: "Holo"
    package_name: "com.github.qiqd.holo"
